name: sub

on:
  workflow_call:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
        type: string
      stage:
        type: string
      branch:
        description: 브랜치
        type: string
      message:
        type: string

jobs:
  sub:
    runs-on: ubuntu-latest
    name: subname ${{ inputs.stage }} / ${{ inputs.branch || github.ref_name }}

    steps:
      - run: |
          echo ${{ inputs.stage }}
          echo ${{ inputs.user_name }}
          echo ${{ inputs.branch || github.ref_name }}
          echo '{"messaeg": "${{ inputs.message }}"}'
          echo '{"messaeg": "${{ toJSON(inputs.message) }}"}'
