on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
      stage:
        type: choice
        options:
        - production
        - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    name: abcd ${{ inputs.stage }}

    steps:
      - run: |
          echo 1 $INPUT_user_name
          echo 2 $INPUT_stage
          echo 3 ${{ inputs.stage }}
          echo 4 ${{ inputs.user_name }}
          
