name: test

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
      stage:
        type: choice
        options:
        - production
        - alpha
      branch:
        type: string

jobs:
  build:
    name: abcd ${{ inputs.stage }}
    uses: ./.github/workflows/sub.yml
    with:
      user_name: ${{ inputs.user_name }}
      stage: ${{ inputs.stage }}
      branch: ${{ inputs.branch }}
  
